- hosts: MySQL app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    sania
  roles:
   - Install_Node_Exporter

  environment:
     http_proxy: http://devopsy.ru:8118
     https_proxy: http://devopsy.ru:8118
