- hosts: runner
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    sania

  roles:
   - gitlab-runner


  environment:
     http_proxy: http://devopsy.ru:8118
     https_proxy: http://devopsy.ru:8118
